/**
 * Weather Pro - FontAwesome Icons & SVG Sprite Generator
 * تزریق آیکون‌های وکتور به حافظه SVG وب‌سایت
 */

import { library, dom } from '@fortawesome/fontawesome-svg-core';
import {
    faArrowRight,
    faCodeCompare,
    faArrowsRotate,
    faAtom,
    faBolt,
    faBottleWater,
    faCalendarDays,
    faChartLine,
    faChevronDown,
    faChevronLeft,
    faChevronRight,
    faCircleCheck,
    faCircleInfo,
    faCircleNotch,
    faCircleXmark,
    faCity,
    faClock,
    faCloudArrowUp,
    faCloudMoon,
    faCloudSunRain,
    faCompass,
    faDroplet,
    faEye,
    faFire,
    faFireFlameCurved,
    faGaugeHigh,
    faHeartPulse,
    faLeaf,
    faLightbulb,
    faLocationArrow,
    faLocationCrosshairs,
    faLocationDot,
    faMagnifyingGlass,
    faMoon,
    faMountainSun,
    faPersonRunning,
    faPersonBiking,
    faBicycle,
    faCamera,
    faHelicopter,
    faSailboat,
    faSolarPanel,
    faBrain,
    faLungs,
    faBone,
    faSeedling,
    faScaleBalanced,
    faShareNodes,
    faShirt,
    faSnowflake,
    faSpinner,
    faStar,
    faSun,
    faTemperatureHalf,
    faTrashCan,
    faTriangleExclamation,
    faUmbrella,
    faWater,
    faWind,
    faXmark,
    faBinoculars,
    faGlasses,
    faSocks,
    faVest,
    faMitten,
    faMask,
    faHatCowboy
} from '@fortawesome/free-solid-svg-icons';

library.add(
    faArrowRight,
    faCodeCompare,
    faArrowsRotate,
    faAtom,
    faBolt,
    faBottleWater,
    faCalendarDays,
    faChartLine,
    faChevronDown,
    faChevronLeft,
    faChevronRight,
    faCircleCheck,
    faCircleInfo,
    faCircleNotch,
    faCircleXmark,
    faCity,
    faClock,
    faCloudArrowUp,
    faCloudMoon,
    faCloudSunRain,
    faCompass,
    faDroplet,
    faEye,
    faFire,
    faFireFlameCurved,
    faGaugeHigh,
    faHeartPulse,
    faLeaf,
    faLightbulb,
    faLocationArrow,
    faLocationCrosshairs,
    faLocationDot,
    faMagnifyingGlass,
    faMoon,
    faMountainSun,
    faPersonRunning,
    faPersonBiking,
    faBicycle,
    faCamera,
    faHelicopter,
    faSailboat,
    faSolarPanel,
    faBrain,
    faLungs,
    faBone,
    faSeedling,
    faScaleBalanced,
    faShareNodes,
    faShirt,
    faSnowflake,
    faSpinner,
    faStar,
    faSun,
    faTemperatureHalf,
    faTrashCan,
    faTriangleExclamation,
    faUmbrella,
    faWater,
    faWind,
    faXmark,
    faBinoculars,
    faGlasses,
    faSocks,
    faVest,
    faMitten,
    faMask,
    faHatCowboy
);

const iconMap = {
    'arrow-right': faArrowRight,
    'arrows-rotate': faArrowsRotate,
    'code-compare': faCodeCompare,
    'atom': faAtom,
    'bolt': faBolt,
    'bottle-water': faBottleWater,
    'calendar-days': faCalendarDays,
    'chart-line': faChartLine,
    'chevron-down': faChevronDown,
    'chevron-left': faChevronLeft,
    'chevron-right': faChevronRight,
    'circle-check': faCircleCheck,
    'circle-info': faCircleInfo,
    'circle-xmark': faCircleXmark,
    'city': faCity,
    'clock': faClock,
    'cloud-arrow-up': faCloudArrowUp,
    'cloud-moon': faCloudMoon,
    'cloud-sun-rain': faCloudSunRain,
    'compass': faCompass,
    'droplet': faDroplet,
    'eye': faEye,
    'fire': faFire,
    'fire-flame-curved': faFireFlameCurved,
    'gauge-high': faGaugeHigh,
    'heart-pulse': faHeartPulse,
    'leaf': faLeaf,
    'lightbulb': faLightbulb,
    'location-arrow': faLocationArrow,
    'location-crosshairs': faLocationCrosshairs,
    'location-dot': faLocationDot,
    'magnifying-glass': faMagnifyingGlass,
    'moon': faMoon,
    'mountain-sun': faMountainSun,
    'person-running': faPersonRunning,
    'person-biking': faPersonBiking,
    'bicycle': faBicycle,
    'camera': faCamera,
    'helicopter': faHelicopter,
    'sailboat': faSailboat,
    'solar-panel': faSolarPanel,
    'brain': faBrain,
    'lungs': faLungs,
    'bone': faBone,
    'seedling': faSeedling,
    'scale-balanced': faScaleBalanced,
    'share-nodes': faShareNodes,
    'shirt': faShirt,
    'snowflake': faSnowflake,
    'spinner': faSpinner,
    'circle-notch': faCircleNotch,
    'star': faStar,
    'sun': faSun,
    'temperature-half': faTemperatureHalf,
    'trash-can': faTrashCan,
    'triangle-exclamation': faTriangleExclamation,
    'umbrella': faUmbrella,
    'water': faWater,
    'wind': faWind,
    'xmark': faXmark,
    'telescope': faBinoculars,
    'glasses': faGlasses,
    'socks': faSocks,
    'vest': faVest,
    'mitten': faMitten,
    'mask': faMask,
    'hat-cowboy': faHatCowboy
};

export function initFontAwesomeIcons() {
    dom.watch();

    const container = document.getElementById('fa-symbols-container');
    if (!container) return;

    let symbolsHTML = `<svg style="display: none;" xmlns="http://www.w3.org/2000/svg">`;

    Object.entries(iconMap).forEach(([name, iconObj]) => {
        const [width, height, , , pathData] = iconObj.icon;
        const paths = Array.isArray(pathData)
            ? pathData.map(p => `<path fill="currentColor" d="${p}"></path>`).join('')
            : `<path fill="currentColor" d="${pathData}"></path>`;

        symbolsHTML += `<symbol id="icon-${name}" viewBox="0 0 ${width} ${height}">${paths}</symbol>`;
    });

    symbolsHTML += `</svg>`;
    container.innerHTML = symbolsHTML;
}
